/* Example program to calculate a grid of points for a Gastner-Newman
 * cartogram using the cartogram.c code
 *
 * Written by Mark Newman
 *
 * See http://www.umich.edu/~mejn/ for further details.
 */


#include <getopt.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cart.h"


/* The parameter OFFSET specifies a small amount to be added the density in
 * every grid square, as a Fraction of the mean density on the whole
 * lattice.  This prevents negative densities from being generated by
 * numerical errors in the FFTs which can cause problems for the
 * integrator.  If the program is giving weird behavior, particularly at
 * the beginning of a calculation, try increasing this quantity by a factor
 * of 10.
 */

#ifndef OFFSET
#  define OFFSET 0.005
#endif

#define INITIAL_POINTS_SIZE 1024

/* Read density data into the array rho.  Returns 1 if there
 * was a problem, zero otherwise */
int readdensity(FILE *stream, double **rho, int xsize, int ysize)
{
  int ix,iy;
  int n;

  for (iy=0; iy < ysize * 3; iy++) {
    for (ix=0; ix < xsize * 3; ix++) {
      rho[ix][iy] = 1.0;
    }
  }

  for (iy=ysize; iy < ysize * 2; iy++) {
    for (ix=xsize; ix < xsize * 2; ix++) {
      n = fscanf(stream, "%lf", &rho[ix][iy]);
      if (n != 1) return 1;
      rho[ix][iy] += OFFSET;
    }
  }

  return 0;
}


/* Load the points. Returns true on error. */
int load_points(FILE *fp, int xsize, int ysize,
                double **points_x_p, double **points_y_p,
                int *npoints) {
  size_t size = 0;
  size_t i;
  int rv = 2;
  
  *points_x_p = *points_y_p = 0;
  for (i=0; rv == 2; i++) {
    if (i+1 > size) {
      if (size == 0) size = INITIAL_POINTS_SIZE; else size *= 2;
      *points_x_p = realloc(*points_x_p, size * sizeof(double));
      *points_y_p = realloc(*points_y_p, size * sizeof(double));
    }
    
    rv = fscanf(fp, "%lg %lg\n", *points_x_p + i, *points_y_p + i);
    (*points_x_p)[i] += xsize;
    (*points_y_p)[i] += ysize;
  }
  
  if (rv == EOF) {
    *npoints = i;
    return 0;
  }
  else if (rv < 2) {
    fprintf(stderr, "Syntax error on line %lu of points file (%d)\n", i+1, rv);
    return 1;
  }
  else {
    fprintf(stderr, "Something impossible happened\n");
    return 1;
  }
}

/* Write out the coordinates of the transformed points */

void writepoints(FILE *stream, double *points_x, double *points_y, int npoints)
{
  int i;
  for (i=0; i<npoints; i++) fprintf(stream,"%g %g\n", points_x[i], points_y[i]);
}

static void usage(char *program_name)
{
    fprintf(stderr, "Usage: %s xsize ysize density-grid points\n", program_name);
    exit(1);
}

int main(int argc, char *argv[])
{
  int xsize,ysize;
  double *points_x, *points_y;  // X and y coordinates of points to be transformed
  int npoints;
  double **rho;                 // Initial density
  FILE *infp;
  FILE *pointsfp;
  char *end_ptr;

  /* options descriptor */
  static struct option longopts[] = {
         { "progress", required_argument, NULL, 'p' }, /* How to display progress */
         { "blur", required_argument, NULL, 'b' },     /* Blur */
         { "max-h", required_argument, NULL, 'm' },    /* Cap on step size */
         { NULL, 0, NULL, 0 }
  };
  options_t options = DEFAULT_OPTIONS;
  char ch;

  while ((ch = getopt_long(argc, argv, "p:m:i", longopts, NULL)) != -1)
    switch (ch) {
      case 'p':
        if (0 == strcmp("none", optarg))
          options.progress_mode = NONE;
        else if (0 == strcmp("normal", optarg))
          options.progress_mode = NORMAL;
        else if (0 == strcmp("percent", optarg))
          options.progress_mode = PERCENT;
        else if (0 == strcmp("detailed", optarg))
          options.progress_mode = DETAILED;
        else {
          fprintf(stderr, "Unrecognised option --progress=%s\n", optarg);
          usage(argv[0]);
        }
        break;
      case 'b':
        options.blur = strtod(optarg, &end_ptr);
        if (*end_ptr != '\0') {
          fprintf(stderr, "Failed to parse number --blur=%s\n", optarg);
          usage(argv[0]);
        }
        break;
      case 'm':
        options.max_h = strtod(optarg, &end_ptr);
        if (*end_ptr != '\0') {
          fprintf(stderr, "Failed to parse number --max-h=%s\n", optarg);
          usage(argv[0]);
        }
        break;
      case 0:
        break;
      default:
        usage(argv[0]);
    }
  
  if ( !isatty(1) )
    setbuf(stdout, NULL);
  
  if (argc != optind+4) usage(argv[0]);
  
  xsize = atoi(argv[optind+0]);
  if (xsize < 1) usage(argv[0]);
  
  ysize = atoi(argv[optind+1]);
  if (ysize < 1) usage(argv[0]);
  
  infp = fopen(argv[optind+2], "r");
  if (infp == NULL) {
    fprintf(stderr,"%s: unable to open file '%s': ",argv[0], argv[optind+2]);
    perror(NULL);
    exit(4);
  }
  
  pointsfp = fopen(argv[optind+3], "r");
  if (pointsfp == NULL) {
    fprintf(stderr,"%s: unable to open file '%s': ",argv[0], argv[optind+3]);
    perror(NULL);
    exit(4);
  }

  /* Allocate space for the cartogram code to use */
  cart_makews(xsize * 3, ysize * 3);

  /* Read in the density data, transform it, then destroy it again */
  rho = cart_dmalloc(xsize * 3, ysize * 3);
  if (readdensity(infp, rho, xsize, ysize)) {
    fprintf(stderr, "%s: density file contains too few or incorrect data\n", argv[0]);
    exit(6);
  }
  fclose(infp);
  cart_transform(rho, xsize * 3, ysize * 3);
  cart_dfree(rho);

  /* Load the points */
  if (load_points(pointsfp, xsize, ysize, &points_x, &points_y, &npoints)) {
    fprintf(stderr, "%s: failed to load points\n", argv[0]);
    exit(7);
  }

  /* Make the cartogram */
  cart_makecart(points_x, points_y, npoints, xsize * 3, ysize * 3, &options);

  /* Write out the final positions of the points */
  writepoints(stdout, points_x, points_y, npoints);

  /* Free up the allocated space */
  cart_freews(xsize, ysize);
  free(points_x);
  free(points_y);
}
